# <h1><center> Basic Python Program 05 </h1></center>

In [3]:
# importing numpy 

import numpy as np

### TASK 01. Write a NumPy program to convert a list and tuple into arrays.

In [4]:
a = [1,2,3,4,5] # list
print(a, type(a))

b = (10,20,30,40,50) # tuple
print(b, type(b))

# Converting a list to ndarray
x = np.array(a)
print(x, type(x))

# Converting a tuple to ndarray
y = np.array(b)
print(y, type(y))

[1, 2, 3, 4, 5] <class 'list'>
(10, 20, 30, 40, 50) <class 'tuple'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[10 20 30 40 50] <class 'numpy.ndarray'>


### TASK 02. Write a NumPy program to append values to the end of an array.

In [5]:
a = np.array([1,2,3,4,5])
a = np.append(a, [6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


### TASK 03. Find the number of elements of an array, length of one array element in bytes

In [6]:
a = np.array([1,2,3,4,5,6])

print("length of the array: ", a.size)
print("Length of one array element in bytes: ", a.itemsize)
print("Total bytes consumed by the elements of the array: ", a.nbytes)

length of the array:  6
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  48


### TASK 04. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 nines.

In [7]:
x = np.zeros(10) # ndarray of 10 zeros
y = np.ones(10) # ndarray of 10 ones
z = np.ones(10) * 9 # ndarray of 10 nines

print(x)
print(y)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]


### TASK 05. Write a NumPy program to create an array of the integers from 30 to 70.

In [8]:
# a = (i for i in range(30,71))

# print(np.fromiter(a,np.int))

In [9]:
new = np.arange(30, 71, 1)
new

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### TASK 06. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [10]:
a = np.array([0,10,20,40,60])
b = np.array([0,40])
    
print('Array1:',a,'\nArray2:',b)
print('Compare each element of array1 and array 2')
print(np.in1d(a,b))

Array1: [ 0 10 20 40 60] 
Array2: [ 0 40]
Compare each element of array1 and array 2
[ True False False  True False]


### TASK 07. Write a NumPy program to find common values between two arrays.

In [12]:
a = np.array([0,10,20,40,60])
b = np.array([10,30,40])

print('Array1:',a,'\nArray2:',b)
print('Common values between two arrays:')
print(np.intersect1d(a,b))

Array1: [ 0 10 20 40 60] 
Array2: [10 30 40]
Common values between two arrays:
[10 40]


### TASK 08. Write a NumPy program to get the unique elements of an array.

In [13]:
a = np.array([10,10,20,20,30,30])

print('Original array:\n',a)
print('Unique elements of the above array:\n', np.unique(a)) 

b = np.array([[1,1],[2,3]])

print('Original array:\n',b)
print('Unique elements of the above array:\n', np.unique(b)) # This prints unique elements of array 'b'

Original array:
 [10 10 20 20 30 30]
Unique elements of the above array:
 [10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array:
 [1 2 3]


### TASK 09. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [12]:
a = np.array([0,10,20,40,60,80])
b = np.array([10,30,40,50,70,90])

print('Array1:',a,'\nArray2:',b)
print('Set difference between two arrays:', np.setdiff1d(a,b))

Array1: [ 0 10 20 40 60 80] 
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


### TASK 10. Write a NumPy program to compute the multiplication of two given matrixes.

In [13]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,11],[20,21],[30,31]])

ans = x.dot(y)
print(ans)

[[140 146]
 [320 335]]
